### PR TITLE
ignore .byebug_history in git

### PR DESCRIPTION
**Pull request by doodzik**
## What are you trying to accomplish?

I was looking into the code with byebug and accidentally committed the .byebug_history on another branch. Since it is pretty common to use byebug to debug code I think it makes sense to add the `.byebug_history` file to the `.gitignore` list.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change that doesn't add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Configuration Change

## Checklist

- [x] It is safe to simply rollback this change.

### CODE REVIEW

**Review by rochlefebvre — APPROVED** [review]
Awesome! I was sitting on the same change. Thanks!

**Comment by tomstuart** [comment]
Since this is the kind of file you want to ignore in every repo, not just `packwerk`, you might want to put it in your [global `.gitignore`](https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer).

**Comment by doodzik** [comment]
> Since this is the kind of file you want to ignore in every repo, not just packwerk, you might want to put it in your global .gitignore.

I think it is an interesting question to ask what belongs to a .gitignore file or not. IMO any file that was added by a dependency of a project should be ignored. In our case we are [defining .byebug as a dependency in the Gemfile](https://github.com/Shopify/packwerk/blob/main/Gemfile#L21). So I think it makes sense to add it to the project's .gitignore file rather than a global one.

**Comment by exterm** [comment]
I agree with Frederik's reasoning here. If it's generated by a dependency specified in this repository, everyone using this repository will have the file so it makes sense to ignore it in the repo.

On the other hand, things like the temporary files that your editor (or any other local tooling) generates should be ignored on your machine, across repos.

**Pull request merged**
