### PR TITLE
Add example & tests for singular / regex inflections

### PR DESCRIPTION
**Pull request by andrewthauer**
## What are you trying to accomplish?

It's not clear or documented how to use regex based `singular` inflection in the custom `inflections.yml` file.

## What approach did you choose and why?

- Added a usage example in docs
- Added example to `custom_inflections.yml` fixture file
- Added explicit test for custom singular inflections that use a regex.

## What should reviewers focus on?

- Proper coverage of test case & validity of example usage

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change that doesn't add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Additional Release Notes

No breaking changes, just clarifying usage and added test cases.

## Checklist

- [x] It is safe to simply rollback this change.

### CODE REVIEW

**Review by doodzik — APPROVED** [review]
LGTM 

Once you sign the CLA and get a second approval we can go ahead and merge this PR.

**Review by exterm — APPROVED** [review]
👏

**Comment by andrewthauer** [comment]
@doodzik, @exterm - The CLA is signed

**Comment by exterm** [comment]
Thank you for your contribution Andrew!

**Pull request merged**
