### PR TITLE
Fix race condition in cache implementation

### PR DESCRIPTION
**Pull request by AlexEvanczuk**
## What are you trying to accomplish?
See https://github.com/Shopify/packwerk/issues/182

## What approach did you choose and why?
More info in issue

## What should reviewers focus on?
Is this an acceptable way to resolve cache race conditions for the short/medium term?

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Non-breaking change (a change that doesn't alter functionality - i.e., code refactor, configs, etc.)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] It is safe to rollback this change.

### CODE REVIEW

**Comment by exterm** [comment]
Is the problem occurring frequently enough in your CI that you can meaningfully test this fix?

**Comment by AlexEvanczuk** [comment]
@exterm It's pretty rare in our CI @exterm -- we're not able to reproduce reliably and haven't even with a scheduled build.

Let me know if you feel hesitations in shipping this and we can think of other strategies.

**Comment by exterm** [comment]
I just encountered it in our CI 🤣 

Yeah I think this doesn't make anything worse (can you think of any drawbacks?) so it's probably fine to just ship it

**Review by exterm — APPROVED** [review]

**Comment by AlexEvanczuk** [comment]
Thanks @exterm ! Maybe we can cut 2.1.1 for this one?

**Pull request merged**
