### PR TITLE
Add .gitkeep for skeleton folder vendor/cache/gems/example/models

### PR DESCRIPTION
**Pull request by wildmaples**
## What are you trying to accomplish?

Fix existing CI failure - https://github.com/Shopify/packwerk/runs/1215182966#step:4:213

## What approach did you choose and why?

Packwerk is expecting a file path at `vendor/cache/gems/example/models` after this PR https://github.com/Shopify/packwerk/pull/21 and there was none, so I created one and added a `.gitkeep`.  

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactor (non-breaking change that doesn't add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Additional Release Notes

Include any notes here to include in the release description. For example, if you selected "breaking change" above, leave notes on how users can transition to this version.

If no additional notes are necessary, delete this section or leave it unchanged.

## Checklist

- [x] It is safe to simply rollback this change.

### CODE REVIEW

**Comment by exterm** [comment]
It's quite strange that branch CI didn't fail.

**Comment by exterm** [comment]
Looking at that other PR I can't even find a CI status... 🤔

**Review by exterm — APPROVED** [review]

**Comment by exterm** [comment]
I made all our status checks required before merging. Maybe that'll prevent something like this from happening in the future.

**Comment by wildmaples** [comment]
@exterm Ya it was odd. All the CI checks passed in #21

**Pull request merged**
