### PR TITLE
Use __dir__ instead of __FILE__

### PR DESCRIPTION
**Pull request by ngan**
## What are you trying to accomplish?
Simplify dir references.

## What approach did you choose and why?
`__FILE__` => `__dir__`

## What should reviewers focus on?
Make sure all paths are 👍 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code refactor (non-breaking change that doesn't add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] It is safe to simply rollback this change.

### CODE REVIEW

**Comment by ngan** [comment]
I've signed the CLA but not sure what's the best way to trigger a rebuild.

**Comment by exterm** [comment]
Mmh, so I'm not super familiar with this yet but I think the CLA status should automatically update once you signed it. Maybe our CLA bot isn't sure that the signer and the PR author are the same person 🤔

**Comment by ngan** [comment]
I opened a different PR after signing: https://github.com/Shopify/packwerk/pull/32 and it passed CLA. Maybe I just need to reopen this PR? Is this something you’d be interested in merging though?

**Comment by exterm** [comment]
Yes, I think it's a valuable change. We need to test it against our monolith before merging it, but it looks good to me. It also looks like CLA bot has now finally woken up and accepted this one.

Sadly it looks like the rest of our CI setup is broken. Working on it.

**Review by tomstuart — APPROVED** [review]
I’ve tested this change against the Shopify monolith and it works fine. 👍  :shipit:

**Comment by tomstuart** [comment]
CI is now fixed on `main`, but that doesn’t help here. I’ve run the checks manually and they pass.

**Pull request merged**
