### PR TITLE
bump packwerk version for new release v1.1.2

### PR DESCRIPTION
**Pull request by rochlefebvre**
## What are you trying to accomplish?
Bump packwerk to v1.1.2 - See [Draft Release](https://github.com/Shopify/packwerk/releases) for the list of relevant changes

## What approach did you choose and why?
Tested on core using `dev packages check`, `dev packages update` (packwerk 1.1.1 and 1.1.2 report the same deprecated references), and `bin/spring packwerk validate`.
Tested on payment-service using `packwerk check`, `packwerk update` and `bin/packwerk validate`.

## What should reviewers focus on?
Are the release notes ok?  Running `bundle update` updates many gems in Gemfile.lock, so I did not do that. I manually incremented the version for `packwerk` instead, as it appears we've done in previous releases.

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Non-breaking change (a change that doesn't alter functionality - i.e., code refactor, configs, etc.)

## Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] It is safe to rollback this change.

### CODE REVIEW

**Comment by doodzik** [comment]
The release notes look good to me. 

I would add that if `bundle update` is bumping many of our dependencies then maybe it is time to just bump them for this release. What do you think?

**Comment by rochlefebvre** [comment]
> The release notes look good to me.
> 
> I would add that if `bundle update` is bumping many of our dependencies then maybe it is time to just bump them for this release. What do you think?

I hesistate to publish a new build right after updating so many dependencies.  How about we release this new version and _then_ I update the dependencies? That will give the new lineup a few weeks of soak time before the next one.

**Comment by doodzik** [comment]
Sounds good to me 👍

**Review by doodzik — APPROVED** [review]

**Review by gmcgibbon — APPROVED** [review]
`bundle update` isn't important for gem releases. The `Gemfile.lock` isn't used when installing the gem. What's important is the constraints you specify in the gem's gemspec. It is up to the consuming app to update its own dependencies.

**Review by exterm — APPROVED** [review]

**Pull request merged**
