### PR TITLE
Don't require Packwerk

### PR DESCRIPTION
**Pull request by gmcgibbon**
## What are you trying to accomplish?

Don't recommend requiring packwerk.

## What approach did you choose and why?

`gem "packwerk", require: false`

## What should reviewers focus on?

Like other static analysis tools, it is not needed when your app boots, so there's no need to require it.

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Non-breaking change (a change that doesn't alter functionality - i.e., code refactor, configs, etc.)

### Additional Release Notes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Include any notes here to include in the release description. For example, if you selected "breaking change" above, leave notes on how users can transition to this version.

If no additional notes are necessary, delete this section or leave it unchanged.

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] It is safe to rollback this change.

### CODE REVIEW

**Review by iwz — APPROVED** [review]
:shipit:

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
Explained in the comment above

**Comment by gmcgibbon** [comment]
> Why?

There is no reason to require a library that is required through an executable script. Rubocop, for example, recommends this in their README so I don't see why Packwerk should be different. Packwerk doesn't slow down boot, but there is zero reason to do it.

**Review by andrewn617 — APPROVED** [review]

**Comment by rafaelfranca** [comment]
I feel like expecting people to pass the `require: false` flag in their Gemfile is a failure in UX of the library. If rubocop does that, I'm sorry for then, but we should not be doing this.

**Comment by exterm** [comment]
Historical context - we actually _needed_ to require packwerk at some point because we injected a custom inflector, so that packwerk would have access to the same inflections that the app uses. I've lost track of whether that's still true.

**Comment by gmcgibbon** [comment]
> I feel like the approach we took with tapioca might be better here.

Packwerk won't inherently disable sorbet with the default require, so there is no action to be done. I'll close since you seem to be opposed to this change. We can monitor it in profiling to see if it really actually needs to happen. If for some reason in the future it does, and it does and we can't optimized away, we can revisit this.

**Pull request closed without merging**
